---
- hosts: localhost
  name: test4
  gather_facts: False
  vars_files:
    - /app/creds.yaml
  module_defaults:
    group/k8s:
      host: "{{ openshift_host }}"
      validate_certs: no

  tasks:
  - name: Test Information
    debug:
      msg: "{{ item }}"
    loop:
      - "Ansible: {{ ansible_version.string }}"
      - "K8S_AUTH_VERIFY_SSL: {{ lookup('env','K8S_AUTH_VERIFY_SSL') }}" 
      - "Test: {{ ansible_play_name}}"
      - "Tests if module_defaults:validate_certs is functioning as expected on k8s_facts"

  - name: Log in
    k8s_auth:
      username: "{{ username }}"
      password: "{{ password }}"
    register: k8s_auth_results
    no_log: true

  - name: Lookup pods
    k8s_facts:
      api_key: "{{ k8s_auth_results.k8s_auth.api_key }}"
      api_version: v1
      kind: Pod
      namespace: default
    no_log: true
