---
- hosts: localhost
  name: test3
  gather_facts: False
  vars_files:
    - /app/creds.yaml
  module_defaults:
    group/k8s:
      host: "{{ openshift_host }}"

  tasks:
  - name: Test Information
    debug:
      msg: "{{ item }}"
    loop:
      - "Ansible: {{ ansible_version.string }}"
      - "K8S_AUTH_VERIFY_SSL: {{ lookup('env','K8S_AUTH_VERIFY_SSL') }}" 
      - "Test: {{ ansible_play_name}} {{ username }}@{{ openshift_host }}"
      - "Expect Success: Tests if validate_certs on log in task is functioning as expected"

  - name: Log in
    k8s_auth:
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: no
    register: k8s_auth_results
    no_log: true
